name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Ejecuta todos los días a la medianoche (UTC)
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Generar snake
        uses: Platane/snk@v3
        with:
          github_user_name: Ing-Dairo
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Subir al repositorio
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

